### ISSUE TITLE
TOra fails to build with Qt 5.11: tohelp.cpp:332:36: error: invalid use of incomplete type ‘class QAction’

### ISSUE THREAD

**Issue by ssten** [tora-tool/tora#101]
Previous fix ([#96](https://github.com/tora-tool/tora/issues/96)) was incomplete, see [653650#c5](https://bugs.gentoo.org/653650#c5) and updated build log for details.

Not found an option to reopen, reporting new issue.

Please, not close before fix is confirmed.

**Comment by ibre5041** [comment]
comme on. it is just a missing header. just fix it, provide a patch and I will apply it.

**Comment by ssten** [comment]
Please, include *tohelp.patch* from referenced bug.

**Comment by ibre5041** [comment]
done
