### ISSUE TITLE
The latest version doesn't compile on Ubuntu 20.10 (Groovy)

### ISSUE THREAD

**Issue by mgogala** [tora-tool/tora#148]
The latest version doesn't compile on Ubuntu 20.10 (Groovy):

/home/mgogala/git/tora/src/views/tobindsview.cpp: In member function ‘virtual QVariant toBindModel::data(const QModelIndex&, int) const’:
/home/mgogala/git/tora/src/views/tobindsview.cpp:72:1: error: jump to label ‘INVALID’

[errors.log](https://github.com/tora-tool/tora/files/5579811/errors.log)
[errors.log](https://github.com/tora-tool/tora/files/5579813/errors.log)
[errors.log](https://github.com/tora-tool/tora/files/5579814/errors.log)

I attached errors.log 3 times, by mistake, I have no idea how to un-attach them.

**Comment by mgogala** [comment]
New commit didn' fix it:

[errors.txt](https://github.com/tora-tool/tora/files/5647956/errors.txt)

/home/mgogala/git/tora/src/views/tobindsview.cpp:72:1: error: jump to label ‘INVALID’
   72 | INVALID:
      | ^~~~~~~
/home/mgogala/git/tora/src/views/tobindsview.cpp:53:14: note:   from here
   53 |         goto INVALID;
      |              ^~~~~~~
/home/mgogala/git/tora/src/views/tobindsview.cpp:64:9: note:   crosses initialization of ‘int c’
   64 |     int c = index.column();

**Comment by keremet** [comment]
this pull request fix the problem https://github.com/tora-tool/tora/pull/152

**Comment by mgogala** [comment]
I can confirm that the problem is now solved.
