### ISSUE TITLE
fails to build with GCC 14

### ISSUE THREAD

**Issue by david-geiger** [tora-tool/tora#164]
Hi,

Current source code fails to build with GCC 14 with the following build issue:

> In file included from /home/pterjan/rpmbuild/BUILD/tora-3.2/extlibs/dtl/dtl/dtl.hpp:44,
                 from /home/pterjan/rpmbuild/BUILD/tora-3.2/src/editor/todifftext.cpp:39:
/home/pterjan/rpmbuild/BUILD/tora-3.2/extlibs/dtl/dtl/Diff.hpp: In member function 'void dtl::Diff<elem, sequence, comparator>::enableTrivial() const':
/home/pterjan/rpmbuild/BUILD/tora-3.2/extlibs/dtl/dtl/Diff.hpp:166:27: error: assignment of member 'trivial' in read-only object
  166 |             this->trivial = true;
      |             ~~~~~~~~~~~~~~^~~~~~

This PR fixes build: https://github.com/cubicdaiya/dtl/pull/18

**Comment by david-geiger** [comment]
Also this PR https://github.com/antlr/antlr3/pull/224 is needed to fix build with embedded libantlr3cpp-3.5.3!

**Comment by atlant2011** [comment]
You probably shouldn't accept this patch, as it changes the program logic.
I've added several patches to PR #168
which fix not only this bug but also other related ones(for GCC-14 & GCC-15).
I also recommend reading https://github.com/tora-tool/tora/issues/166

**Comment by david-geiger** [comment]
Always this build issue with latest git qt6 branch and your PR #168:

> In file included from /home/david/SVN/cauldron/tora/BUILD/tora-3.2-build/tora-5dddc9965d857df9031aff50243d97701374a485/extlibs/dtl/dtl/dtl.hpp:44,
                 from /home/david/SVN/cauldron/tora/BUILD/tora-3.2-build/tora-5dddc9965d857df9031aff50243d97701374a485/src/editor/todifftext.cpp:39:
/home/david/SVN/cauldron/tora/BUILD/tora-3.2-build/tora-5dddc9965d857df9031aff50243d97701374a485/extlibs/dtl/dtl/Diff.hpp: In member function 'void dtl::Diff<elem, sequence, comparator>::enableTrivial() const':
/home/david/SVN/cauldron/tora/BUILD/tora-3.2-build/tora-5dddc9965d857df9031aff50243d97701374a485/extlibs/dtl/dtl/Diff.hpp:166:27: error: assignment of member 'trivial' in read-only object [-Wtemplate-body]
  166 |             this->trivial = true;
      |             ~~~~~~~~~~~~~~^~~~~~

**Comment by atlant2011** [comment]
Not tested with trunk qt. Only qtbase-6.10.2 .
How version gcc? /me test with gcc-14 (Gentoo 14.3.1_p20260213 p5) & gcc-15 (Gentoo 15.2.1_p20260214 p5)
Update 1.
It turns out I didn't include a patch from the previous ones (not made by me).
I'll try adding it today. It's a simple patch.
In file dtl/Diff.hpp b/dtl/Diff.hpp
replace 
    void enableTrivial () const {
to
    void enableTrivial () {

**Comment by atlant2011** [comment]
Apply patch for fix "void enableTrivial () ". PR #168 refreshed.
Test it's.
