### ISSUE TITLE
Build fails on Ubuntu 19.10

### ISSUE THREAD

**Issue by mgogala** [tora-tool/tora#141]
Here is what happens when I attempt to build tora on 19.10:

Git version v3.2-278-g316e3a90
Git version major 3
Git version minor 2
Git version count 278
Git version sha1  g316e3a90
Git version short 3.2
Git version dirty No
Git branch master
Build tag v3.2-278-Release-g316e3a90
Build date 2020-03-22
Omitting deprecated element <images>.
/home/mgogala/git/tora/src/widgets/todatabasesettingui.ui: Warning: The name 'gridLayout' (QGridLayout) is already in use, defaulting to 'gridLayout4'.
/home/mgogala/git/tora/src/core/tocontextmenu.h:0: Note: No relevant classes found. No output generated.
/home/mgogala/git/tora/src/core/tohelpcontext.h:0: Note: No relevant classes found. No output generated.
/home/mgogala/git/tora/src/core/tosettingtab.h:0: Note: No relevant classes found. No output generated.
/home/mgogala/git/tora/src/parsing/toscilexersql.h:0: Note: No relevant classes found. No output generated.
/home/mgogala/git/tora/src/tools/tosecuritytreeitem.h:0: Note: No relevant classes found. No output generated.
/home/mgogala/git/tora/src/widgets/toconnectionwidget.h:0: Note: No relevant classes found. No output generated.
In file included from /home/mgogala/git/tora/src/core/toconfenum.h:39,
                 from /home/mgogala/git/tora/src/core/toconfiguration.h:37,
                 from /home/mgogala/git/tora/src/main/main.cpp:35:
/home/mgogala/git/tora/src/main/main.cpp: In function ‘int main(int, char**)’:
/home/mgogala/git/tora/src/ts_log/ts_log_utils.h:46:38: note: #pragma message: WARNING: TODO/FIXME: hicolor theme is broken for Docklet icons. But we need to resolve X11 themes one day
   46 | #   define WARN(exp) ("WARNING: " exp)
      |                                      ^
/home/mgogala/git/tora/src/main/main.cpp:119:17: note: in expansion of macro ‘WARN’
  119 | #pragma message WARN( "TODO/FIXME: hicolor theme is broken for Docklet icons. But we need to resolve X11 themes one day" )
      |                 ^~~~
In file included from /home/mgogala/git/BUILD/src/widgets/moc_totableview.cpp:9:
/home/mgogala/git/BUILD/src/widgets/../../../tora/src/widgets/totableview.h: In member function ‘void Views::DefaultTableViewPolicy<_T>::setup(Views::DefaultTableViewPolicy<_T>::View*)’:
/home/mgogala/git/BUILD/src/widgets/../../../tora/src/widgets/totableview.h:132:64: error: incomplete type ‘QHeaderView’ used in nested name specifier
  132 |     pView->verticalHeader()->setSectionResizeMode(QHeaderView::Fixed);
      |                                                                ^~~~~
/home/mgogala/git/BUILD/src/widgets/../../../tora/src/widgets/totableview.h:135:66: error: incomplete type ‘QHeaderView’ used in nested name specifier
  135 |     pView->horizontalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);
      |                                                                  ^~~~~~~~~~~~~~~~
make[3]: *** [src/CMakeFiles/tora.dir/build.make:3206: src/CMakeFiles/tora.dir/widgets/moc_totableview.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:266: src/CMakeFiles/tora.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:278: src/CMakeFiles/tora.dir/rule] Error 2
make: *** [Makefile:238: tora] Error 2

**Comment by mkyral** [comment]
I have the same issue on Gentoo after upgrade QT libs to v5.14
```
# qlop -mv dev-qt/qtgui
...
2020-01-03T13:56:47 >>> dev-qt/qtgui-5.13.2
2020-03-28T01:04:12 >>> dev-qt/qtgui-5.14.1-r3
```

```
[ 61%] Building CXX object src/CMakeFiles/tora.dir/widgets/moc_ExtendedTabWidget.cpp.o
cd /var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/src && /usr/bin/x86_64-pc-linux-gnu-g++ -DHAVE_GITREVISION_H=1 -DHAVE_POSTGRESQL_LIBPQ_FE_H -DLIBPQ_DECL_CANCEL -DNDEBUG -DORACLE_OCI_VER_11G -DPROVIDERS_PATH=\"/usr/lib64/tora-3.2\" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_THREAD_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSHARE_DIR=\"/usr/share/tora-3.2\" -DTOBUILDTYPE_RELEASE=1 -DTROTL_DLL -DTSQLPARSER_DLL -Dtora_EXPORTS -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/src -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999/src -I/usr/include/FerrisLoki -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999/extlibs/loki-extra/include -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999 -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999/src/precompiled -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999/extlibs/trotl/src -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999/extlibs/libermodel -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999/extlibs/libantlr3cpp-3.5.3/include -I/var/tmp/portage/dev-db/tora-9999/work/tora-9999/extlibs/dtl -I/usr/lib64/oracle/11.2.0.4/client/rdbms/public -I/usr/include/qt5/Qsci -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml   -DNDEBUG -march=native -O2 -pipe -ggdb -ggdb -ggdb -ggdb -ggdb -fPIE   -DQT -DSCI_LEXER -fPIC -std=gnu++11 -o CMakeFiles/tora.dir/widgets/moc_ExtendedTabWidget.cpp.o -c /var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/src/widgets/moc_ExtendedTabWidget.cpp
In file included from /var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/src/widgets/moc_totableview.cpp:10:
/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/src/widgets/../../../tora-9999/src/widgets/totableview.h: In member function ‘void Views::DefaultTableViewPolicy<_T>::setup(Views::DefaultTableViewPolicy<_T>::View*)’:
/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/src/widgets/../../../tora-9999/src/widgets/totableview.h:132:64: error: incomplete type ‘QHeaderView’ used in nested name specifier
  132 |     pView->verticalHeader()->setSectionResizeMode(QHeaderView::Fixed);
      |                                                                ^~~~~
/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/src/widgets/../../../tora-9999/src/widgets/totableview.h:135:66: error: incomplete type ‘QHeaderView’ used in nested name specifier
  135 |     pView->horizontalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);
      |                                                                  ^~~~~~~~~~~~~~~~
[ 62%] Building CXX object src/CMakeFiles/tora.dir/widgets/moc_toabout.cpp.o
```

**Comment by mgogala** [comment]
Yes, this builds TOra, but not "poracle":

make: *** No rule to make target 'poracle'.  Stop

**Comment by mgogala** [comment]
My mistake. Oracle has changed the structure of the instant client and my path to the includes was wrong. I fixed it and now I have a fully successful build on top of  the Instant Client 19.5.
Thanks!
